---
# install DNSmasq and HAProxy on s0.infra
- hosts: control
  tasks:
    - name: install DNSmasq
      apt:
        name: ['dnsmasq']
        state: present
    - name: update cache haproxy
      apt: 
        update_cache: yes
        cache_valid_time: 3600

    - name: install haproxy
      apt:
        name: haproxy
        state: present
        
        #- name: restart haproxy
        #service: 
        # name: haproxy
        #state: started

    - name: Enable init script
      replace: 
        dest='/etc/default/haproxy'
        regexp='ENABLED=0'
        replace='ENABLED=1'

    - name: configure HAProxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: vagrant
        group: vagrant
        

# install Apache and PHP on s1 and s2.infra
- hosts: web
  tasks:
    - name: install apache and php
      apt:
        name: ['apache2', 'php7.3', 'nfs-common']
        state: present

# install MariaDB on s3
- hosts: db
  tasks:
    - name: install mariadb
      apt:
        name: "{{ item }}"
        state: present
      with_items:
          - mariadb-client
          - mariadb-common
          - mariadb-server
    - name: Create Mariadb directories
      file: 
        path: /data/{{item}}
        state: directory
        owner: mysql
        group: mysql
        recurse: yes
      with_items:
        - db
        - log
     - name: Write new configuration file
       template:
         src: templates/mysql
         dest: /etc/mysql/my.cnf


# install nfs on s4.infra
- hosts: nfs
  tasks:
    - name: install nfs on s4
      apt:
        name: ['nfs-kernel-server', 'nfs-common']
        state: present
